#!/bin/bash
echo "Lab 4 tests ********************"
for test in 41 42 43 44 45a 45b 45c 45d 45e 45f 46 48 49 ; do
    test5a/runt test$test
done

echo "Lab 5a tests ********************"
for test in 1a 1b 2a 2b 3 4a 4b 5a 5b 6; do
    test5a/runt test$test
done

